name: Build and Deploy to Static Repo

on:
  push:
    branches: ["master", "main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Public Repo
        env:
          API_TOKEN_GITHUB: ${{ secrets.DEPLOY_TOKEN }}
        run: |
          cd dist
          git init
          git config user.name "shadowmind1337"
          git config user.email "shadowmind1337@gmail.com"
          git add .
          git commit -m "Deploy build to static repo"
          git push --force https://x-access-token:${API_TOKEN_GITHUB}@github.com/boilerplate1/panel-static.git master:main
