name: Build and Deploy to Cloudflare Pages

on:
  push:
    branches: ["master", "main"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build
        env:
          VITE_API_URL: https://prod-v1-api.umbr.rest/api
          VITE_RECAPTCHA_SITE_KEY: 0x4AAAAAADksO24nf-9vXTAc
          VITE_ANDROID_APK_URL: https://hpxvpn.xyz/downloads/hypexvpn.apk
        run: npm run build

      - name: Verify Build
        run: ls -R dist

      - name: Deploy to Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          echo "Checking wrangler version..."
          npx wrangler --version
          echo "Deploying to Pages..."
          npx wrangler pages deploy dist --project-name=hypex-frontend --branch=master
